#pragma once
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <algorithm>
#include <map>
#include <tuple>
#include "Car.h"
#include "Order.h"
#include "Plane.h"
#include "Track.h"
#include "Train.h"
#include "Type.h"
#include "Data.h"
#include "TransportManager.h"